speilberg = Director.create(name: "Steven Speilberg", dob: "1946-12-18", description: "Solid")
del_toro = Director.create(name: "Guillermo del Toro", dob: "1964-10-09" , description: "Action-Packed")
soderbergh = Director.create(name: "Steven Soderbergh", dob: "1963-01-14", description: "Strange")
scott = Director.create(name: "Ridley Scott", dob: "1937-12-30", description: "Awesome")
del_toro.movies.create(name: "Pacific Rim", release_date: "2013-07-12", rating: 7.3, length: 131, description: "Sweet")
del_toro.movies.create(name: "Blade II", release_date: "2002-03-22", rating: 6.6, length: 117, description: "Weird")
speilberg.movies.create(name: "Amistad", release_date: "1997-12-10", rating: 7.1, length: 155, description: "Dark")
speilberg.movies.create(name: "Schindler's List", release_date: "1993-12-15", rating: 8.9, length: 195, description: "Depressing")
soderbergh.movies.create(name: "Magic Mike", release_date: "2012-06-29", rating: 6.1, length: 110, description: "I Don't Even Know Where to Begin...")
speilberg.movies.create(name: "Catch Me If You Can", release_date: "2002-12-25", rating: 7.9, length:141, description: "Cunning")
soderbergh.movies.create(name: "Ocean's Thirteen", release_date: "2007-06-08", rating: 6.8, length: 122, description: "Redeemed the Series")
soderbergh.movies.create(name: "Behind the Candelabra", release_date: "2013-06-07", rating: 7.0, length: 118, description: "HBO")
scott.movies.create(name: "Gladiator", release_date: "2000-03-05", rating: 8.5, length: 255, description: "Are You Entertained?")
scott.movies.create(name: "Black Hawk Down", release_date: "2002-01-18", rating: 7.7, length: 144, description: "War")
speilberg.movies.create(name: "Saving Private Ryan", release_date: "1998-07-24", rating: 8.6, length: 169, description: "Intense")
