Director.create(name: "Stanley Kubrick", img: "http://www.kasterine.com/KUBRICK/images/kubrick_smiling_copy_jpg.jpg", dob: "1928-07-26", description: "American film director, screenwriter, producer, cinematographer, and editor who did most of his work as an expatriate in the United Kingdom. He is regarded as one of the greatest filmmakers of all time. His films, typically adaptations of novels or short stories, are noted for their dazzling and unique cinematography, attention to details to achieve realism and an inspired use of music scores. Kubricks films covered a variety of genres, including war, crime, romantic and black comedies, horror, epic and science fiction.")

Director.create(name: "Orson Welles", img: "http://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Orson_Welles_1937.jpg/440px-Orson_Welles_1937.jpg", dob: "1915-05-06", description: "His first film was Citizen Kane (1941), which he co-wrote, produced, directed, and starred in as Charles Foster Kane. Welles was an outsider to the studio system and directed only 13 full-length films in his career. While he struggled for creative control in the face of studios, his films were heavily edited and others remained unreleased. His distinctive directorial style featured layered and nonlinear narrative forms, innovative uses of lighting such as chiaroscuro, unusual camera angles, sound techniques borrowed from radio, deep focus shots, and long takes.")

Movie.create(name: "2001: A Space Odyssey", release: "1968-04-02", rating: 10, length: 142, director_id: 1, description: "Thematically, the film deals with elements of human evolution, technology, artificial intelligence, and extraterrestrial life. It is notable for its scientific accuracy, pioneering special effects, ambiguous imagery, sound in place of traditional narrative techniques, and minimal use of dialogue.")

Movie.create(name: "Barry Lyndon", release: "1975-12-18", rating: 10, length: 184, description: "Barry Lyndon is a 1975 British-American period film starring Ryan O'Neal, Marisa Berenson, Murray Melvin, Patrick Magee and Hardy Krüger. It was written, produced, and directed by Stanley Kubrick. The film is based on the 1844 novel The Luck of Barry Lyndon by William Makepeace Thackeray which recounts the exploits of a fictional 18th-century Irish adventurer.", director_id: 1)

Movie.create(name: "The Shining", release: "1980-05-23", length: 143, rating: 10, description: "The Shining is a 1980 British-American psychological horror film produced and directed by Stanley Kubrick, co-written with novelist Diane Johnson, and starring Jack Nicholson, Shelley Duvall, Danny Lloyd, and Scatman Crothers. The film is based on Stephen King's novel of the same name.", director_id: 1)

Movie.create(name: "Touch of Evil", release: "1958-5-21", length: 112, rating: 10, description: "The film opens with a three-minute, twenty-second tracking shot widely considered by critics as one of the greatest long takes in cinematic history. On the U.S.-Mexico border, a man plants a time bomb in a car. A man and woman enter the vehicle and make a slow journey through town to the U.S. border. Newlyweds Miguel Mike Vargas (Charlton Heston) and Susie (Janet Leigh) pass the car several times on foot. The car crosses the border, then explodes, killing the occupants.", director_id: 2 )

Movie.create(name: "Chimes at Midnight", release: "1965-12-22", rating: 7, length: 119, description: "Welles said that the core of the film's story was the betrayal of friendship. It stars Welles as Falstaff, Keith Baxter as Prince Hal, John Gielgud as Henry IV, Jeanne Moreau as Doll Tearsheet and Margaret Rutherford as Mistress Quickly. The script contains text from five of Shakespeare's plays; primarily Henry IV, Part 1 and Henry IV, Part 2, but also Richard II, Henry V, and uses some dialogue from The Merry Wives of Windsor. Ralph Richardson's narration is taken from the works of chronicler Raphael Holinshed.", director_id: 2)

Movie.create(name: "The Lady from Shanghai", release: "1947-12-24", length: 87, rating: 10, description: "The Lady from Shanghai is a 1947 film noir directed by Orson Welles and starring Welles, his estranged wife Rita Hayworth and Everett Sloane. It is based on the novel If I Die Before I Wake by Sherwood King.", director_id: 2)
