
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ImdbCopy_development
  pool: 5
  
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ImdbCopy_test
  pool: 5
