Director.create(name: 'Sofia Coppola', description: 'Oscar-winner and renowned director of moody, visually opulent, candy-color-bright films with discordant music and introspective characters.') # birthday: 14/9/1971)
Director.create(name: 'Nora Ephron', description: 'Three time oscar nominee and creator of such classics as youve got mail, sleepless in seattle, and when harry met sally, Nora Ephron is a legend.') # birthday: 19/9/1941)
Director.create(name: 'Terrence Malik', description: 'Reclusive and exacting master of emotion-evoking imagery, releases films only one or twice a decade, resides in Austin, Texas, has not yet won an Oscar.') # birthday: 30/11/1943)
Director.create(name: 'David Fincher', description: 'Dark and unforgiving movies, as well as sentimental, political, and tech-culture films, have made Fincher a director whose projects you go see no matter what.') # birthday: 28/8/1962)

Movie.create(name: 'Marie Antoinette', description: 'Bonbons and guillotines and punk music.', rating: '6.3')
Movie.create(name: 'Days of Heaven', description: 'House on a hill in a field, love, lust, murder.', rating: '7.9')
Movie.create(name: 'When Harry Met Sally', description: 'Two people, one friendship, many chances at love.', rating: '7.6')
Movie.create(name: 'Fight Club', description: 'First rule of fight club: you dont talk about fight club.', rating: '8.8')
Movie.create(name: 'Panic Room', description: 'Jodi Foster and Kristen Stewart plus reinforced conrete defeat NYC burglars.', rating: '6.8')
Movie.create(name: 'Sleepless in Seattle', description: 'A kid calls into a radio show after his mom dies, and ends up on the empire state building waiting for the love of his dad;s life.', rating: '6.7')
Movie.create(name: 'The Thin Red Line', description: 'Through Whits eyes, we see war and life as intertwined, not exactly opposites, but uneasy partners.', rating: '7.6')
Movie.create(name: 'The Virgin Suicides', description: 'Nightgowns, religion, teenage girl legs, and suicide.', rating: '7.2')